version: '3'
services:
  nginx:
    image: nginx-release
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /data/certbot/conf:/etc/letsencrypt
      - /data/certbot/www:/var/www/certbot
    networks:
      - nginx
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - /data/certbot/conf:/etc/letsencrypt
      - /data/certbot/www:/var/www/certbot
networks:
  nginx:
    name: nginx
