version: '3'
services:
  nginx:
    image: nginx-release
    container_name: nginx
    build:
      context: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /data/certbot/conf:/etc/letsencrypt
      - /data/certbot/www:/var/www/certbot
    networks:
      - nginx
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - /data/certbot/conf:/etc/letsencrypt
      - /data/certbot/www:/var/www/certbot
    entrypoint:
      - certbot
      - certonly
      - --non-interactive
      - --webroot
      - --webroot-path=/var/www/certbot
      - --email=wisq@wisq.net
      - --domains=ismypowerbackyet.com
      - --rsa-key-size=4096
      - --agree-tos
      - --no-eff-email
networks:
  nginx:
    name: nginx
